package app.tabletracker.features.companion.model

const val ACTION_REQUEST_SERVER_ADDRESS = "action.REQUEST_SERVER_ADDRESS"
const val ACTION_SERVER_ADDRESS_AVAILABLE = "action.SERVER_ADDRESS_AVAILABLE"
const val EXTRA_SERVER_ADDRESS = "extra.SERVER_ADDRESS"
const val ACTION_CLIENT_CONNECTED = "action.CLIENT_CONNECTED"

const val ACTION_REQUEST_SERVER_CONNECTION = "action.REQUEST_SERVER_CONNECTION"
const val ACTION_SERVER_CONNECTION_AVAILABLE = "action.SERVER_CONNECTION_AVAILABLE"
const val EXTRA_SERVER_CONNECTION = "extra.SERVER_CONNECTION"